import { images } from "../../assets/images/image";

const jsonData = [
  {
    title: "Ooblets",
    date: "9/1/22",
    buttonText: null,
    saleEnd: null,
    text: "nintendo Switch",
    price: "$19.99",
    originalPrice: "$29.99",
    // salePercentage: 30,
    image: images.card1,
  },
  {
    title: "Title 2",
    date: "Date 2",
    buttonText: "Button Text 2",
    saleEnd: 3,
    text: "Text 2",
    price: "$24.99",
    originalPrice: "$34.99",
    salePercentage: 20,
    image: images.card2,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card3,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card4,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card5,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card6,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card7,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card8,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card9,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card10,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card11,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card12,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card13,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card14,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card15,
  },
  {
    title: "Title 3",
    date: "Date 3",
    buttonText: "Button Text 3",
    saleEnd: 7,
    text: "Text 3",
    price: "$14.99",
    originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card16,
  },
];

export default jsonData;
