import { images } from "../../assets/images/image";

const jsonData = [
  {
    title: "Ooblets",
    date: "9/1/22",
    buttonText: null,
    saleEnd: null,
    text: "nintendo Switch",
    price: "$19.99",
    originalPrice: "$29.99",
    // salePercentage: 30,
    image: images.card1,
  },
  {
    title: "Potion Permit",
    date: "9/2/22",
    // buttonText: "Button Text 2",
    // saleEnd: 3,
    text: "nintendo Switch",
    price: "$19.99",
    // originalPrice: "$34.99",
    // salePercentage: 20,
    image: images.card2,
  },
  {
    title: "Cozy Grove",
    date: "4/8/21",
    buttonText: "sales ends: 1hr",
    saleEnd: 7,
    text: "nintendo Switch",
    price: "$8.50",
    originalPrice: "$14.99",
    salePercentage: 45,
    image: images.card3,
  },
  {
    title: "Animal Crossing: new Horizons",
    date: "3/20/20",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$59.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card4,
  },
  {
    title: "My Time at Portia",
    date: "4/16/19",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$29.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card5,
  },
  {
    title: "Disney DreamLight Valley",
    date: "9.6/22",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$39.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card6,
  },
  {
    title: "EA Sport FiFa 23 Nintendo Switch Legacy Edition",
    date: "9/3/22",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$39.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card7,
  },
  {
    title: "Story Of Seasons: A Wonderful life",
    date: "6/27/23",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$39.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card8,
  },
  {
    title: "NBA 2k23",
    date: "9/9/22",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$59.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card9,
  },
  {
    title: "Turnip Boy Commits Tax Evasion",
    date: "4/22/21",
    // buttonText: "Button Text 3",
    saleEnd: 7,
    text: "nintendo Switch",
    price: "$5.09",
    originalPrice: "$14.99",
    salePercentage: 66,
    image: images.card10,
  },
  {
    title: "Story Of Seasons: Pioneers of Olive Town",
    date: "3/23/21",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$39.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card11,
  },
  {
    title: "MLB The Show 22",
    date: "4/5/22",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$59.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card12,
  },
  {
    title: "Calico",
    date: "12/15/20",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$11.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card13,
  },
  {
    title: "Dragon Quest Builders 2",
    date: "7/12/19",
    buttonText: "Free demo",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$49.99",
    // originalPrice: "$19.99",
    // salePercentage: 25,
    image: images.card14,
  },
  {
    title: "Yonder: The cloud Catcher Chronicles",
    date: "5/17/18",
    // buttonText: "Button Text 3",
    saleEnd: 1,
    text: "nintendo Switch",
    price: "$8.99",
    originalPrice: "$29.99",
    salePercentage: 70,
    image: images.card15,
  },
  {
    title: "Subnautica: Below Zero",
    date: "5/14/21",
    // buttonText: "Button Text 3",
    // saleEnd: 7,
    text: "nintendo Switch",
    price: "$29.99",
    // originalPrice: "$19.99",
    salePercentage: 25,
    image: images.card16,
  },
];

export default jsonData;
